name: Linter

# Run this workflow every time a new commit pushed to your repository
on: pull_request

jobs:
  linter:
    # Name the Job
    name: Detekt
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Detekt
        run: ./gradlew detekt
